package com.supply.supplyTrace.alert;

public enum AlertType {
    NEW_SCRIPT,
    REMOVED_SCRIPT,
    NEW_STYLESHEET,
    REMOVED_STYLESHEET,
    NEW_IFRAME,
    REMOVED_IFRAME,
    NEW_PLUGIN,
    REMOVED_PLUGIN,
    NEW_DOMAIN,
    REMOVED_DOMAIN,
    RAW_IP_RESOURCE,
    HTTP_MIXED_CONTENT,
    SUSPICIOUS_DOMAIN,
    TOO_MANY_THIRD_PARTY_DOMAINS,
    SITE_UNREACHABLE,
    RISK_SCORE_HIGH
}

